### ISSUE TITLE
Running out of space for build.

### ISSUE THREAD

**Issue by jayacotton** [Laci1953/RTM-Z80#1]
I have built all but rtsys.as in situ.   

CP/M 2.2 running on an SC131.  

D>zas rtsys.as
RTSYS.AS:1456:  Out of memory

I have  55302 Bytes in TPA.

**Comment by Laci1953** [comment]
Solved, see github for the new rtsys1.as and rtsys2.as, plus new make.subLadislau
    On Saturday, August 14, 2021, 05:09:35 AM GMT+3, Jay Cotton ***@***.***> wrote:  
 
 


I have built all but rtsys.as in situ.

CP/M 2.2 running on an SC131.

D>zas rtsys.as
RTSYS.AS:1456: Out of memory

I have 55302 Bytes in TPA.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
