### ISSUE TITLE
Running out of memory again.

### ISSUE THREAD

**Issue by jayacotton** [Laci1953/RTM-Z80#3]
I am building this on the SC131 hardware, not using UDO's z80sim.

D>b:submit make

D>D:
D>ZAS -J DLIST.AS

D>ZAS -J BALLOC.AS

D>ZAS RTSYS1.AS
RTSYS1.AS:6:    Can't open include file config.mac

D>ZAS -J RTSYS2.AS
config.mac:110: No space for macro def'n

D>ZAS -J RTCLK.AS
config.mac:289: No space for macro def'n

D>ZAS -J QUEUE.AS

D>ZAS -J MAILBOX.AS

D>ZAS -J IO.AS
IO.AS:11:       Can't open include file config.mac

D>ZAS -J SNAPSHOT.AS

D>ZAS -J HEXLOAD.AS
config.mac:280: No space for macro def'n

D>ZAS -J UTIL.AS

D>ZAS -J CMD.AS

D>ZAS BOOT.AS

D>ZAS -J CSV.AS

D>ERA RT.LIB
D>LIBR R RT.LIB RTSYS1.OBJ RTSYS2.OBJ CMD.OBJ SNAPSHOT.OBJ 
bad file format: RTSYS1.OBJ
unknown record type: 26

D>LIBR R RT.LIB HEXLOAD.OBJ IO.OBJ QUEUE.OBJ RTCLK.OBJ MAILBOX.OBJ
module HEXLOAD.OBJ defines no symbols (warning)
bad file format: IO.OBJ
unknown record type: 26

D>LIBR R RT.LIB BALLOC.OBJ DLIST.OBJ UTIL.OBJ BOOT.OBJ CSV.OBJ
module BOOT.OBJ defines no symbols (warning)

**Comment by Laci1953** [comment]
Hi Jay,
again, too many GLOBAL's and MACRO...
I uploaded some changes, in SOURCES (new files: leds.mac and ramrom.mac )
I hope this version will compile :)
Ladislau
    On Saturday, August 21, 2021, 09:04:05 AM GMT+3, Jay Cotton ***@***.***> wrote:  
 
 


I am building this on the SC131 hardware, not using UDO's z80sim.

D>b:submit make

D>D:
D>ZAS -J DLIST.AS

D>ZAS -J BALLOC.AS

D>ZAS RTSYS1.AS
RTSYS1.AS:6: Can't open include file config.mac

D>ZAS -J RTSYS2.AS
config.mac:110: No space for macro def'n

D>ZAS -J RTCLK.AS
config.mac:289: No space for macro def'n

D>ZAS -J QUEUE.AS

D>ZAS -J MAILBOX.AS

D>ZAS -J IO.AS
IO.AS:11: Can't open include file config.mac

D>ZAS -J SNAPSHOT.AS

D>ZAS -J HEXLOAD.AS
config.mac:280: No space for macro def'n

D>ZAS -J UTIL.AS

D>ZAS -J CMD.AS

D>ZAS BOOT.AS

D>ZAS -J CSV.AS

D>ERA RT.LIB
D>LIBR R RT.LIB RTSYS1.OBJ RTSYS2.OBJ CMD.OBJ SNAPSHOT.OBJ
bad file format: RTSYS1.OBJ
unknown record type: 26

D>LIBR R RT.LIB HEXLOAD.OBJ IO.OBJ QUEUE.OBJ RTCLK.OBJ MAILBOX.OBJ
module HEXLOAD.OBJ defines no symbols (warning)
bad file format: IO.OBJ
unknown record type: 26

D>LIBR R RT.LIB BALLOC.OBJ DLIST.OBJ UTIL.OBJ BOOT.OBJ CSV.OBJ
module BOOT.OBJ defines no symbols (warning)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jayacotton** [comment]
Closer but still not there.
D>submit make

D>ZAS -J DLIST.AS

D>ZAS -J BALLOC.AS

D>ZAS RTSYS1.AS
config.mac:132: No space for macro def'n

D>ZAS -J RTSYS2.AS
config.mac:141: No space for macro def'n

D>ZAS -J RTCLK.AS

D>ZAS -J QUEUE.AS

D>ZAS -J MAILBOX.AS

D>ZAS -J IO.AS

D>ZAS -J SNAPSHOT.AS

D>ZAS -J HEXLOAD.AS

D>ZAS -J UTIL.AS

D>ZAS -J CMD.AS

D>ZAS BOOT.AS

D>ZAS -J CSV.AS

D>ERA RT.LIB
D>LIBR R RT.LIB RTSYS1.OBJ RTSYS2.OBJ CMD.OBJ SNAPSHOT.OBJ 
bad file format: RTSYS1.OBJ
unknown record type: 26

D>LIBR R RT.LIB HEXLOAD.OBJ IO.OBJ QUEUE.OBJ RTCLK.OBJ MAILBOX.OBJ
module HEXLOAD.OBJ defines no symbols (warning)

D>LIBR R RT.LIB BALLOC.OBJ DLIST.OBJ UTIL.OBJ BOOT.OBJ CSV.OBJ
module BOOT.OBJ defines no symbols (warning)

**Comment by Laci1953** [comment]
Solved

**Comment by jayacotton** [comment]
Yes.  It is now fixed.
